# Fine-tune Chinese-BERT with finance semantic contrast data on Kaggle.
#
# Purpose:
#   Continue from the existing Chinese-BERT text-risk checkpoint and add a
#   finance semantic contrast set: realistic oral normal-finance hard negatives
#   plus same-vocabulary fraud positives. This avoids training only on explicit
#   "do not give verification codes" safety-advice sentences.
#
# Baseline compatibility:
#   - Reuses the TeleAntiFraud loading, dedup, label convention, and
#     ChineseBERTClassifier architecture from baseline-of-chinese-bert.py.
#   - Reuses the gradient training/checkpoint style from
#     ChineseBERTModel/train_chinese_bert_kaggle.py.
#
# Expected Kaggle inputs:
#   1. TeleAntiFraud-28k dataset directory.
#   2. finance_semantic_contrast_train_val.jsonl generated by
#      evaluation/generate_benign_finance_hard_negatives.py.
#   3. Optional but recommended: current baseline best_model.pt/train.pt.
#   4. Optional for no-internet Kaggle runs: a local bert-base-chinese folder.
#
# Label convention:
#   text_label=1 means phishing/fraud semantics.
#   text_label=0 means benign text semantics, even if it contains finance words.

from __future__ import annotations

import json
import logging
import os
import random
import re
import warnings
from collections import Counter
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader, Dataset
from tqdm.auto import tqdm
from transformers import AutoModel, AutoTokenizer


warnings.filterwarnings("ignore")
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)


CONFIG: Dict[str, Any] = {
    "teleantifraud_data_root": os.environ.get(
        "TELEANTIFRAUD_DATA_ROOT",
        "/kaggle/input/teleantifraud-28k/TeleAntiFraud/JimmyMa99/TeleAntiFraud-28k/TeleAntiFraud-28k/TeleAntiFraud-28k",
    ),
    "semantic_contrast_data_path": os.environ.get(
        "SEMANTIC_CONTRAST_DATA_PATH",
        os.environ.get(
            "HARD_NEGATIVE_DATA_PATH",
            "/kaggle/input/datasets/samueltmsun/finance-semantic-contrast-hard-set/finance_semantic_contrast_train_val.jsonl",
        ),
    ),
    "model_name": os.environ.get("CHINESE_BERT_MODEL_NAME", "bert-base-chinese"),
    "init_checkpoint_path": os.environ.get("CHINESE_BERT_INIT_CHECKPOINT", ""),
    "output_dir": os.environ.get("FINETUNE_OUTPUT_DIR", "/kaggle/working/hard_negative_finetune"),
    "model_save_dir": os.environ.get("FINETUNE_MODEL_DIR", "/kaggle/working/hard_negative_finetune/model"),
    "max_len": int(os.environ.get("CHINESE_BERT_MAX_LEN", "256")),
    "hidden_size": 768,
    "num_classes": 2,
    "dr_rate": float(os.environ.get("CHINESE_BERT_DROPOUT", "0.3")),
    "batch_size": int(os.environ.get("CHINESE_BERT_BATCH_SIZE", "16")),
    "num_epochs": int(os.environ.get("CHINESE_BERT_EPOCHS", "3")),
    "learning_rate": float(os.environ.get("CHINESE_BERT_LR", "1e-5")),
    "weight_decay": float(os.environ.get("CHINESE_BERT_WEIGHT_DECAY", "0.01")),
    "warmup_ratio": float(os.environ.get("CHINESE_BERT_WARMUP_RATIO", "0.1")),
    "test_size": float(os.environ.get("TELEANTIFRAUD_VAL_SIZE", "0.15")),
    "extra_normal_repeat": int(os.environ.get("EXTRA_NORMAL_REPEAT", os.environ.get("HARD_NEGATIVE_REPEAT", "10"))),
    "extra_fraud_repeat": int(os.environ.get("EXTRA_FRAUD_REPEAT", "8")),
    "tele_train_max_per_class": int(os.environ.get("TELE_TRAIN_MAX_PER_CLASS", "6000")),
    "threshold": float(os.environ.get("CHINESE_BERT_THRESHOLD", "50")),
    "seed": int(os.environ.get("CHINESE_BERT_SEED", "42")),
}

TEXT_COLUMNS = (
    "text",
    "full_asr_text",
    "metadata_text",
    "transcript_text",
    "full_text",
    "content",
    "utterance",
)
TEXT_LABEL_COLUMNS = ("text_label", "semantic_label", "label")
INIT_CHECKPOINT_CANDIDATES = (
    "/kaggle/input/chinese-bert-baseline-model/best_model.pt",
    "/kaggle/input/chinese-bert-baseline-model/train.pt",
    "/kaggle/input/chinese-bert-model/best_model.pt",
    "/kaggle/input/chinese-bert-model/train.pt",
    "/kaggle/input/notebooks/samueltmsun/fork-of-chinese-bert/model/best_model.pt",
    "/kaggle/input/notebooks/samueltmsun/fork-of-chinese-bert/model/train.pt",
    "/kaggle/working/model/best_model.pt",
    "/kaggle/working/model/train.pt",
)


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False


def normalize_text_for_dedup(value: Any) -> str:
    text = str(value or "").strip()
    text = re.sub(r"\s+", "", text)
    text = re.sub(r"[，。！？；：,.!?;:（）()\[\]{}【】\"'“”‘’·…—\-_/\\|<>~`@#$%^&*+=]", "", text)
    text = re.sub(r"(甲|乙|客户|客服|工作人员)[:：]", "", text)
    return text.lower()


def parse_binary_label(value: Any) -> int:
    text = str(value).strip().lower()
    if text in {"1", "1.0", "true", "fraud", "phishing", "scam", "risk", "risky"}:
        return 1
    if text in {"0", "0.0", "false", "normal", "benign", "safe"}:
        return 0
    return int(float(value))


def read_json_records(path: Path) -> List[Dict[str, Any]]:
    raw = path.read_text(encoding="utf-8").strip()
    if not raw:
        return []
    if path.suffix.lower() == ".jsonl":
        return [json.loads(line) for line in raw.splitlines() if line.strip()]
    payload = json.loads(raw)
    if isinstance(payload, list):
        return [row for row in payload if isinstance(row, dict)]
    if isinstance(payload, dict) and isinstance(payload.get("records"), list):
        return [row for row in payload["records"] if isinstance(row, dict)]
    raise ValueError(f"Unsupported JSON schema: {path}")


def find_first_data_file(path_value: str) -> Path:
    path = Path(path_value)
    if path.is_file():
        return path
    if path.is_dir():
        for pattern in ("*.jsonl", "*.csv", "*.json"):
            candidates = sorted(path.glob(pattern))
            if candidates:
                return candidates[0]
    raise FileNotFoundError(f"No CSV/JSON/JSONL data file found at {path_value}")


def column_or_default(df: pd.DataFrame, column: str, default: Any) -> pd.Series:
    if column in df.columns:
        return df[column]
    return pd.Series([default] * len(df), index=df.index)


def load_semantic_contrast_data(path_value: str) -> pd.DataFrame:
    path = find_first_data_file(path_value)
    print(f"Loading semantic contrast data: {path}")
    if path.suffix.lower() == ".csv":
        raw_df = pd.read_csv(path)
    else:
        raw_df = pd.DataFrame(read_json_records(path))
    if raw_df.empty:
        raise ValueError(f"No rows loaded from semantic contrast data: {path}")

    text_col = next((col for col in TEXT_COLUMNS if col in raw_df.columns), None)
    label_col = next((col for col in TEXT_LABEL_COLUMNS if col in raw_df.columns), None)
    if text_col is None:
        raise ValueError(f"Semantic contrast data needs one text column from: {TEXT_COLUMNS}")
    if label_col is None:
        raise ValueError(f"Semantic contrast data needs text_label/semantic_label/label")

    df = pd.DataFrame()
    df["sample_id"] = column_or_default(
        raw_df,
        "sample_id",
        "",
    ).fillna("")
    missing_ids = df["sample_id"].astype(str).str.len().eq(0)
    df.loc[missing_ids, "sample_id"] = [f"hardneg_{idx:05d}" for idx in df.index[missing_ids]]
    df["text"] = raw_df[text_col].fillna("").astype(str).str.strip()
    df["text_label"] = raw_df[label_col].apply(parse_binary_label).astype(int)
    df["split"] = column_or_default(raw_df, "split", "").fillna("").astype(str).str.lower()
    df["case_type"] = column_or_default(raw_df, "case_type", "finance_semantic_contrast")
    df["source"] = column_or_default(raw_df, "source", "semantic_contrast_extra")
    df["scenario"] = column_or_default(raw_df, "scenario", "unknown")
    df = df[df["text"].str.len() > 0].copy()
    bad_labels = sorted(set(df["text_label"].unique()) - {0, 1})
    if bad_labels:
        raise ValueError(f"Semantic contrast data contains non-binary labels: {bad_labels}")

    if not df["split"].isin({"train", "val"}).all():
        train_df, val_df = train_test_split(df, test_size=0.2, random_state=CONFIG["seed"], shuffle=True)
        train_df = train_df.copy()
        val_df = val_df.copy()
        train_df["split"] = "train"
        val_df["split"] = "val"
        df = pd.concat([train_df, val_df], ignore_index=True)

    df["norm"] = df["text"].apply(normalize_text_for_dedup)
    before = len(df)
    df = df.drop_duplicates(subset=["norm"], keep="first").drop(columns=["norm"]).reset_index(drop=True)
    print(f"Semantic contrast rows loaded: {len(df)} (deduplicated {before - len(df)})")
    print(df["split"].value_counts().to_string())
    print(df["text_label"].value_counts().sort_index().to_string())
    print(df["source"].value_counts().sort_index().to_string())
    print(df["scenario"].value_counts().sort_index().to_string())
    return df


class TeleAntiFraudDataLoader:
    def __init__(self, data_root: str):
        self.data_root = Path(data_root)
        self.merged_result_dir = self.data_root / "merged_result"

    @staticmethod
    def _label_from_dirname(dirname: str) -> Optional[int]:
        upper = dirname.upper()
        if upper.startswith("NEG"):
            return 1
        if upper.startswith("POS"):
            return 0
        return None

    @staticmethod
    def _parse_config_jsonl(filepath: Path) -> Optional[str]:
        try:
            raw = filepath.read_text(encoding="utf-8").strip()
            if not raw:
                return None
            data = json.loads(raw)
        except Exception:
            return None

        segments = data.get("audio_segments", [])
        if not segments:
            return None

        parts = []
        for seg in segments:
            role = seg.get("role", "unknown")
            content = str(seg.get("content", "")).strip()
            if not content:
                continue
            speaker = "甲" if role == "left" else "乙" if role == "right" else "未知"
            parts.append(f"{speaker}：{content}")
        text = "\n".join(parts).strip()
        return text if len(text) >= 10 else None

    def load_merged_result(self) -> pd.DataFrame:
        rows: List[Dict[str, Any]] = []
        if not self.merged_result_dir.exists():
            logger.warning(f"merged_result not found: {self.merged_result_dir}")
            return pd.DataFrame(rows)

        for category_dir in sorted(d for d in self.merged_result_dir.iterdir() if d.is_dir()):
            label = self._label_from_dirname(category_dir.name)
            if label is None:
                continue
            for sample_dir in sorted(d for d in category_dir.iterdir() if d.is_dir()):
                candidates = [sample_dir / "config.jsonl"]
                candidates.extend(sorted(sample_dir.glob("*.jsonl")))
                candidates.extend(sorted(sample_dir.glob("*.json")))
                config_file = next((path for path in candidates if path.exists()), None)
                if config_file is None:
                    continue
                text = self._parse_config_jsonl(config_file)
                if text is None:
                    continue
                rows.append(
                    {
                        "sample_id": sample_dir.name,
                        "text": text,
                        "text_label": label,
                        "case_type": "teleantifraud_fraud" if label == 1 else "teleantifraud_normal",
                        "source": "teleantifraud",
                        "scenario": category_dir.name,
                    }
                )
        return pd.DataFrame(rows)

    def load_top_level_jsonl(self) -> pd.DataFrame:
        rows: List[Dict[str, Any]] = []
        for jsonl_file in sorted(self.data_root.glob("*.jsonl")):
            with jsonl_file.open("r", encoding="utf-8") as handle:
                for line_num, line in enumerate(handle, 1):
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        data = json.loads(line)
                    except json.JSONDecodeError:
                        continue
                    segments = data.get("audio_segments", [])
                    if not segments:
                        continue
                    parts = []
                    for seg in segments:
                        role = seg.get("role", "unknown")
                        content = str(seg.get("content", "")).strip()
                        if content:
                            speaker = "甲" if role == "left" else "乙"
                            parts.append(f"{speaker}：{content}")
                    text = "\n".join(parts)
                    if len(text) < 10:
                        continue
                    label: Optional[int] = None
                    tts_id = str(data.get("tts_id", "")).lower()
                    if "fraud" in tts_id:
                        label = 1
                    elif "normal" in tts_id:
                        label = 0
                    if label is None:
                        name = jsonl_file.name.lower()
                        if "neg" in name:
                            label = 1
                        elif "pos" in name:
                            label = 0
                    if label is None:
                        continue
                    rows.append(
                        {
                            "sample_id": f"{jsonl_file.stem}_{line_num}",
                            "text": text,
                            "text_label": label,
                            "case_type": "teleantifraud_fraud" if label == 1 else "teleantifraud_normal",
                            "source": "teleantifraud_top_jsonl",
                            "scenario": jsonl_file.name,
                        }
                    )
        return pd.DataFrame(rows)

    def load_all(self) -> pd.DataFrame:
        print(f"TeleAntiFraud root: {self.data_root}")
        merged_df = self.load_merged_result()
        if not merged_df.empty:
            df = merged_df
        else:
            df = self.load_top_level_jsonl()
        if df.empty:
            raise ValueError(f"No TeleAntiFraud samples loaded from {self.data_root}")
        df["text_label"] = df["text_label"].astype(int)
        df["text"] = df["text"].fillna("").astype(str).str.strip()
        df = df[df["text"].str.len() > 0].copy()
        df["norm"] = df["text"].apply(normalize_text_for_dedup)
        conflict_norms = df.groupby("norm")["text_label"].nunique()
        conflict_norms = set(conflict_norms[conflict_norms > 1].index)
        if conflict_norms:
            print(f"Dropping {len(conflict_norms)} conflicting normalized text groups from TeleAntiFraud")
            df = df[~df["norm"].isin(conflict_norms)].copy()
        before = len(df)
        df = df.drop_duplicates(subset=["norm"], keep="first").drop(columns=["norm"]).reset_index(drop=True)
        print(f"TeleAntiFraud loaded: {len(df)} (deduplicated {before - len(df)})")
        print(df["text_label"].value_counts().sort_index().to_string())
        return df


def split_teleantifraud(df: pd.DataFrame) -> Tuple[pd.DataFrame, pd.DataFrame]:
    train_df, val_df = train_test_split(
        df,
        test_size=CONFIG["test_size"],
        random_state=CONFIG["seed"],
        stratify=df["text_label"],
    )
    train_df = train_df.copy()
    val_df = val_df.copy()
    train_df["split"] = "train"
    val_df["split"] = "val"
    max_per_class = int(CONFIG["tele_train_max_per_class"])
    if max_per_class > 0:
        parts = []
        for label, group in train_df.groupby("text_label"):
            if len(group) > max_per_class:
                group = group.sample(n=max_per_class, random_state=CONFIG["seed"] + int(label))
            parts.append(group)
        train_df = pd.concat(parts, ignore_index=True).sample(frac=1.0, random_state=CONFIG["seed"]).reset_index(drop=True)
    return train_df.reset_index(drop=True), val_df.reset_index(drop=True)


def build_train_val_data(tele_df: pd.DataFrame, extra_df: pd.DataFrame) -> Tuple[pd.DataFrame, pd.DataFrame]:
    tele_train, tele_val = split_teleantifraud(tele_df)
    extra_train = extra_df[extra_df["split"].eq("train")].copy()
    extra_val = extra_df[extra_df["split"].eq("val")].copy()
    if extra_train.empty or extra_val.empty:
        raise ValueError("Semantic contrast data must contain both train and val rows.")

    repeated_parts = []
    for label, repeat in ((0, int(CONFIG["extra_normal_repeat"])), (1, int(CONFIG["extra_fraud_repeat"]))):
        label_df = extra_train[extra_train["text_label"].astype(int).eq(label)].copy()
        if label_df.empty:
            continue
        repeated = pd.concat([label_df] * max(1, repeat), ignore_index=True)
        repeated["repeat_source"] = "oversampled_semantic_contrast"
        repeated["repeat_factor"] = repeat
        repeated_parts.append(repeated)
    if not repeated_parts:
        raise ValueError("Semantic contrast train split does not contain usable rows.")
    repeated_extra_train = pd.concat(repeated_parts, ignore_index=True)

    train_df = pd.concat([tele_train, repeated_extra_train], ignore_index=True)
    val_df = pd.concat([tele_val, extra_val], ignore_index=True)
    train_df = train_df.sample(frac=1.0, random_state=CONFIG["seed"]).reset_index(drop=True)
    val_df = val_df.sample(frac=1.0, random_state=CONFIG["seed"]).reset_index(drop=True)

    summary_rows = []
    for split_name, split_df in (("train", train_df), ("val", val_df)):
        for source, group in split_df.groupby("source"):
            counts = Counter(group["text_label"].astype(int).tolist())
            summary_rows.append(
                {
                    "split": split_name,
                    "source": source,
                    "samples": len(group),
                    "label_0": counts.get(0, 0),
                    "label_1": counts.get(1, 0),
                }
            )
    summary = pd.DataFrame(summary_rows)
    output_dir = Path(CONFIG["output_dir"])
    output_dir.mkdir(parents=True, exist_ok=True)
    summary.to_csv(output_dir / "data_mix_summary.csv", index=False, encoding="utf-8-sig")
    print("Data mix summary:")
    print(summary.to_string(index=False))
    return train_df, val_df


class ChineseBERTClassifier(nn.Module):
    def __init__(self, bert_model: nn.Module, hidden_size: int = 768, num_classes: int = 2, dr_rate: float = 0.3):
        super().__init__()
        self.bert = bert_model
        self.dropout = nn.Dropout(p=dr_rate)
        self.classifier = nn.Linear(hidden_size, num_classes)

    def forward(
        self,
        input_ids: torch.Tensor,
        attention_mask: torch.Tensor,
        token_type_ids: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:
        outputs = self.bert(
            input_ids=input_ids,
            token_type_ids=token_type_ids,
            attention_mask=attention_mask,
            return_dict=True,
        )
        pooled_output = getattr(outputs, "pooler_output", None)
        if pooled_output is None:
            pooled_output = outputs.last_hidden_state[:, 0, :]
        return self.classifier(self.dropout(pooled_output))


class FraudTextDataset(Dataset):
    def __init__(self, df: pd.DataFrame, tokenizer: Any, max_len: int):
        self.texts = df["text"].fillna("").astype(str).tolist()
        self.labels = df["text_label"].astype(int).tolist()
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self) -> int:
        return len(self.texts)

    def __getitem__(self, idx: int) -> Dict[str, torch.Tensor]:
        encoding = self.tokenizer(
            self.texts[idx],
            padding="max_length",
            truncation=True,
            max_length=self.max_len,
            return_tensors="pt",
        )
        token_type_ids = encoding.get("token_type_ids", torch.zeros_like(encoding["input_ids"]))
        return {
            "input_ids": encoding["input_ids"].squeeze(0),
            "attention_mask": encoding["attention_mask"].squeeze(0),
            "token_type_ids": token_type_ids.squeeze(0),
            "label": torch.tensor(self.labels[idx], dtype=torch.long),
        }


def resolve_init_checkpoint(path_value: str) -> Optional[Path]:
    if path_value:
        path = Path(path_value)
        if not path.exists():
            raise FileNotFoundError(f"Configured init checkpoint does not exist: {path}")
        return path
    for candidate in INIT_CHECKPOINT_CANDIDATES:
        path = Path(candidate)
        if path.exists():
            return path
    return None


def load_model_and_tokenizer(device: torch.device) -> Tuple[ChineseBERTClassifier, Any, Optional[Path]]:
    print(f"Loading tokenizer/base model: {CONFIG['model_name']}")
    tokenizer = AutoTokenizer.from_pretrained(CONFIG["model_name"])
    bert = AutoModel.from_pretrained(CONFIG["model_name"])
    model = ChineseBERTClassifier(
        bert,
        hidden_size=CONFIG["hidden_size"],
        num_classes=CONFIG["num_classes"],
        dr_rate=CONFIG["dr_rate"],
    ).to(device)
    checkpoint = resolve_init_checkpoint(str(CONFIG.get("init_checkpoint_path", "")))
    if checkpoint is not None:
        print(f"Continuing from baseline checkpoint: {checkpoint}")
        state = torch.load(checkpoint.as_posix(), map_location=device)
        missing, unexpected = model.load_state_dict(state, strict=False)
        if missing:
            print(f"Warning: missing keys when loading checkpoint: {missing}")
        if unexpected:
            print(f"Warning: unexpected keys when loading checkpoint: {unexpected}")
    else:
        print("No baseline checkpoint found. Training starts from the pretrained BERT encoder.")
    return model, tokenizer, checkpoint


def binary_metrics(y_true: Sequence[int], scores: Sequence[float], threshold: float) -> Dict[str, Any]:
    y_true_arr = np.array(y_true, dtype=int)
    score_arr = np.array(scores, dtype=float)
    y_pred = (score_arr >= threshold).astype(int)
    tn, fp, fn, tp = confusion_matrix(y_true_arr, y_pred, labels=[0, 1]).ravel()
    try:
        auc_value: Any = roc_auc_score(y_true_arr, score_arr) if len(set(y_true_arr.tolist())) > 1 else ""
    except Exception:
        auc_value = ""
    return {
        "samples": int(len(y_true_arr)),
        "accuracy": round(float(accuracy_score(y_true_arr, y_pred)), 4),
        "precision": round(float(precision_score(y_true_arr, y_pred, zero_division=0)), 4),
        "recall": round(float(recall_score(y_true_arr, y_pred, zero_division=0)), 4),
        "f1": round(float(f1_score(y_true_arr, y_pred, zero_division=0)), 4),
        "roc_auc": round(float(auc_value), 4) if auc_value != "" else "",
        "tn": int(tn),
        "fp": int(fp),
        "fn": int(fn),
        "tp": int(tp),
        "normal_fp_rate": round(float(fp / max(1, (y_true_arr == 0).sum())), 4),
        "fraud_recall": round(float(tp / max(1, (y_true_arr == 1).sum())), 4),
    }


@torch.no_grad()
def predict_validation(
    model: ChineseBERTClassifier,
    loader: DataLoader,
    device: torch.device,
) -> Tuple[List[int], List[int], List[float], float]:
    model.eval()
    targets: List[int] = []
    preds: List[int] = []
    scores: List[float] = []
    total_loss = 0.0
    criterion = nn.CrossEntropyLoss()
    for batch in tqdm(loader, desc="Validation", unit="batch"):
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        token_type_ids = batch["token_type_ids"].to(device)
        labels = batch["label"].to(device)
        logits = model(input_ids, attention_mask, token_type_ids)
        total_loss += criterion(logits, labels).item()
        probs = F.softmax(logits, dim=-1)[:, 1]
        batch_scores = (probs.detach().cpu().numpy() * 100.0).tolist()
        scores.extend(batch_scores)
        preds.extend((np.array(batch_scores) >= float(CONFIG["threshold"])).astype(int).tolist())
        targets.extend(labels.detach().cpu().tolist())
    return targets, preds, scores, total_loss / max(1, len(loader))


def build_validation_report(val_df: pd.DataFrame, scores: Sequence[float]) -> Tuple[pd.DataFrame, pd.DataFrame, Dict[str, float]]:
    pred_df = val_df.copy().reset_index(drop=True)
    pred_df["bert_score"] = np.array(scores, dtype=float)
    pred_df["pred_label"] = (pred_df["bert_score"] >= float(CONFIG["threshold"])).astype(int)
    pred_df["is_error"] = pred_df["pred_label"].ne(pred_df["text_label"].astype(int))

    rows = []
    overall = binary_metrics(pred_df["text_label"], pred_df["bert_score"], float(CONFIG["threshold"]))
    overall.update({"scope": "overall", "group": "all"})
    rows.append(overall)
    for source, group in pred_df.groupby("source", dropna=False):
        row = binary_metrics(group["text_label"], group["bert_score"], float(CONFIG["threshold"]))
        row.update({"scope": "source", "group": source})
        rows.append(row)
    for case_type, group in pred_df.groupby("case_type", dropna=False):
        row = binary_metrics(group["text_label"], group["bert_score"], float(CONFIG["threshold"]))
        row.update({"scope": "case_type", "group": case_type})
        rows.append(row)
    metrics_df = pd.DataFrame(rows)

    extra_mask = pred_df["source"].astype(str).str.startswith("semantic_contrast") | pred_df["case_type"].astype(str).str.contains(
        "finance", case=False, na=False
    )
    normal_hard_val = pred_df[extra_mask & pred_df["text_label"].astype(int).eq(0)]
    contrast_fraud_val = pred_df[extra_mask & pred_df["text_label"].astype(int).eq(1)]

    hard_fp_rate = float(normal_hard_val["pred_label"].mean()) if len(normal_hard_val) else 0.0
    hard_tnr = 1.0 - hard_fp_rate
    contrast_fraud_recall = float(contrast_fraud_val["pred_label"].mean()) if len(contrast_fraud_val) else 0.0
    objective = 0.4 * float(overall["f1"]) + 0.35 * hard_tnr + 0.25 * contrast_fraud_recall
    selection = {
        "overall_f1": float(overall["f1"]),
        "overall_recall": float(overall["recall"]),
        "semantic_contrast_normal_tnr": hard_tnr,
        "semantic_contrast_normal_fp_rate": hard_fp_rate,
        "semantic_contrast_fraud_recall": contrast_fraud_recall,
        "semantic_contrast_normal_samples": int(len(normal_hard_val)),
        "semantic_contrast_fraud_samples": int(len(contrast_fraud_val)),
        "selection_score": objective,
    }
    return pred_df, metrics_df, selection


def save_epoch_outputs(
    epoch: int,
    pred_df: pd.DataFrame,
    metrics_df: pd.DataFrame,
    selection: Dict[str, float],
    output_dir: Path,
) -> None:
    epoch_dir = output_dir / f"epoch_{epoch:02d}"
    epoch_dir.mkdir(parents=True, exist_ok=True)
    pred_df.to_csv(epoch_dir / "val_predictions.csv", index=False, encoding="utf-8-sig")
    metrics_df.to_csv(epoch_dir / "val_metrics.csv", index=False, encoding="utf-8-sig")
    extra_mask = pred_df["source"].astype(str).str.startswith("semantic_contrast") | pred_df["case_type"].astype(str).str.contains(
        "finance", case=False, na=False
    )
    contrast_fp = pred_df[extra_mask & pred_df["text_label"].eq(0) & pred_df["pred_label"].eq(1)].copy()
    contrast_fn = pred_df[extra_mask & pred_df["text_label"].eq(1) & pred_df["pred_label"].eq(0)].copy()
    contrast_fp.to_csv(epoch_dir / "semantic_contrast_val_false_positives.csv", index=False, encoding="utf-8-sig")
    contrast_fn.to_csv(epoch_dir / "semantic_contrast_val_false_negatives.csv", index=False, encoding="utf-8-sig")
    contrast_fp.to_csv(epoch_dir / "hard_negative_val_false_positives.csv", index=False, encoding="utf-8-sig")
    (epoch_dir / "selection_metrics.json").write_text(json.dumps(selection, indent=2), encoding="utf-8")


def train() -> None:
    set_seed(int(CONFIG["seed"]))
    output_dir = Path(CONFIG["output_dir"])
    model_save_dir = Path(CONFIG["model_save_dir"])
    output_dir.mkdir(parents=True, exist_ok=True)
    model_save_dir.mkdir(parents=True, exist_ok=True)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")
    if torch.cuda.is_available():
        props = torch.cuda.get_device_properties(0)
        print(f"GPU: {props.name} ({props.total_memory / 1024**3:.2f} GB)")

    tele_df = TeleAntiFraudDataLoader(CONFIG["teleantifraud_data_root"]).load_all()
    extra_df = load_semantic_contrast_data(CONFIG["semantic_contrast_data_path"])
    train_df, val_df = build_train_val_data(tele_df, extra_df)

    model, tokenizer, init_checkpoint = load_model_and_tokenizer(device)
    train_dataset = FraudTextDataset(train_df, tokenizer, int(CONFIG["max_len"]))
    val_dataset = FraudTextDataset(val_df, tokenizer, int(CONFIG["max_len"]))
    train_loader = DataLoader(train_dataset, batch_size=int(CONFIG["batch_size"]), shuffle=True, num_workers=2)
    val_loader = DataLoader(val_dataset, batch_size=int(CONFIG["batch_size"]), shuffle=False, num_workers=2)

    label_counts = Counter(train_df["text_label"].astype(int).tolist())
    if label_counts[0] and label_counts[1]:
        weight_for_0 = len(train_df) / (2 * label_counts[0])
        weight_for_1 = len(train_df) / (2 * label_counts[1])
        class_weights = torch.tensor([weight_for_0, weight_for_1], dtype=torch.float32).to(device)
        criterion = nn.CrossEntropyLoss(weight=class_weights)
        print(f"Class weights: normal={weight_for_0:.4f}, fraud={weight_for_1:.4f}")
    else:
        criterion = nn.CrossEntropyLoss()

    optimizer = optim.AdamW(model.parameters(), lr=float(CONFIG["learning_rate"]), weight_decay=float(CONFIG["weight_decay"]))
    total_steps = max(1, len(train_loader) * int(CONFIG["num_epochs"]))
    scheduler = optim.lr_scheduler.OneCycleLR(
        optimizer,
        max_lr=float(CONFIG["learning_rate"]),
        total_steps=total_steps,
        pct_start=float(CONFIG["warmup_ratio"]),
    )

    logs: List[Dict[str, Any]] = []
    best_selection_score = -1.0
    best_epoch = -1
    best_model_path = model_save_dir / "best_model.pt"

    for epoch in range(1, int(CONFIG["num_epochs"]) + 1):
        model.train()
        train_targets: List[int] = []
        train_preds: List[int] = []
        train_loss_total = 0.0
        for batch in tqdm(train_loader, desc=f"Epoch {epoch}/{CONFIG['num_epochs']} train", unit="batch"):
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            token_type_ids = batch["token_type_ids"].to(device)
            labels = batch["label"].to(device)

            optimizer.zero_grad()
            logits = model(input_ids, attention_mask, token_type_ids)
            loss = criterion(logits, labels)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()
            scheduler.step()

            train_loss_total += loss.item()
            train_targets.extend(labels.detach().cpu().tolist())
            train_preds.extend(torch.argmax(logits, dim=1).detach().cpu().tolist())

        train_loss = train_loss_total / max(1, len(train_loader))
        train_acc = accuracy_score(train_targets, train_preds)
        train_f1 = f1_score(train_targets, train_preds, zero_division=0)

        val_targets, val_preds, val_scores, val_loss = predict_validation(model, val_loader, device)
        pred_df, metrics_df, selection = build_validation_report(val_df, val_scores)
        save_epoch_outputs(epoch, pred_df, metrics_df, selection, output_dir)

        log_entry = {
            "epoch": epoch,
            "train_loss": round(float(train_loss), 6),
            "train_acc": round(float(train_acc), 4),
            "train_f1": round(float(train_f1), 4),
            "val_loss": round(float(val_loss), 6),
            "val_acc": round(float(accuracy_score(val_targets, val_preds)), 4),
            "val_precision": round(float(precision_score(val_targets, val_preds, zero_division=0)), 4),
            "val_recall": round(float(recall_score(val_targets, val_preds, zero_division=0)), 4),
            "val_f1": round(float(f1_score(val_targets, val_preds, zero_division=0)), 4),
            "semantic_contrast_normal_fp_rate": round(float(selection["semantic_contrast_normal_fp_rate"]), 4),
            "semantic_contrast_fraud_recall": round(float(selection["semantic_contrast_fraud_recall"]), 4),
            "selection_score": round(float(selection["selection_score"]), 4),
            "lr": scheduler.get_last_lr()[0],
        }
        logs.append(log_entry)
        pd.DataFrame(logs).to_csv(output_dir / "training_log.csv", index=False, encoding="utf-8-sig")

        print(
            f"Epoch {epoch}: train_loss={train_loss:.4f}, val_f1={log_entry['val_f1']:.4f}, "
            f"val_recall={log_entry['val_recall']:.4f}, "
            f"contrast_normal_fp={log_entry['semantic_contrast_normal_fp_rate']:.4f}, "
            f"contrast_fraud_recall={log_entry['semantic_contrast_fraud_recall']:.4f}, "
            f"selection={log_entry['selection_score']:.4f}"
        )

        if selection["selection_score"] > best_selection_score:
            best_selection_score = float(selection["selection_score"])
            best_epoch = epoch
            torch.save(model.state_dict(), best_model_path)
            pred_df.to_csv(output_dir / "best_val_predictions.csv", index=False, encoding="utf-8-sig")
            metrics_df.to_csv(output_dir / "best_val_metrics.csv", index=False, encoding="utf-8-sig")
            print(f"Saved best model at epoch {epoch}: {best_model_path}")

    final_model_path = model_save_dir / "train.pt"
    torch.save(model.state_dict(), final_model_path)

    config_save = {
        **CONFIG,
        "init_checkpoint_used": str(init_checkpoint) if init_checkpoint else "",
        "best_epoch": best_epoch,
        "best_selection_score": best_selection_score,
        "train_samples": len(train_df),
        "val_samples": len(val_df),
        "train_label_counts": dict(Counter(train_df["text_label"].astype(int).tolist())),
        "val_label_counts": dict(Counter(val_df["text_label"].astype(int).tolist())),
        "selection_metric": "0.4 * overall_val_f1 + 0.35 * semantic_contrast_normal_tnr + 0.25 * semantic_contrast_fraud_recall",
    }
    (model_save_dir / "training_config.json").write_text(json.dumps(config_save, indent=2), encoding="utf-8")

    print("Fine-tuning complete.")
    print(f"Best model: {best_model_path} (epoch {best_epoch}, selection={best_selection_score:.4f})")
    print(f"Final model: {final_model_path}")
    print(f"Training log: {output_dir / 'training_log.csv'}")
    print(f"Best validation metrics: {output_dir / 'best_val_metrics.csv'}")
    print("Download model/best_model.pt and copy it locally as ChineseBERTModel/model/train.pt for system testing.")


if __name__ == "__main__":
    train()
